[build]
  command = "npm run netlify-build"
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]

# Redirect для пользователей
[[redirects]]
  from = "/users/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Redirect для категорий 
[[redirects]]
  from = "/categories/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
