[build]
  command = "npm run netlify-build"
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]

# Redirect для авторизации
[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Redirect для пользователей
[[redirects]]
  from = "/users/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Redirect для категорий 
[[redirects]]
  from = "/categories/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/default-avatar.png"
  to = "/default-avatar.png"
  status = 200

[[redirects]]
  from = "/default-category.jpg" 
  to = "/default-category.jpg"
  status = 200